# Generated by Django 5.0.7 on 2024-08-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Карера')),
            ],
            options={
                'verbose_name': 'Карера',
                'verbose_name_plural': 'Кареры',
            },
        ),
        migrations.CreateModel(
            name='Catigori_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Катигория отзыва')),
            ],
            options={
                'verbose_name': 'Катигория отзыва',
                'verbose_name_plural': 'Катигории отзывов',
            },
        ),
        migrations.CreateModel(
            name='Cauntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр фильма')),
            ],
            options={
                'verbose_name': 'Жанр фильма',
                'verbose_name_plural': 'Жанры фильмов',
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('heght', models.PositiveBigIntegerField(verbose_name='Рост')),
                ('date_fo_birth', models.DateField(verbose_name='Дата родждения')),
                ('total_movis', models.PositiveBigIntegerField(default=0, verbose_name='Всего филемов')),
                ('active_years', models.PositiveIntegerField(verbose_name='Cтаж')),
                ('total_save', models.PositiveBigIntegerField(default=0, verbose_name='Количество избранном')),
                ('career', models.ManyToManyField(related_name='career', to='movie.career', verbose_name='Карера')),
                ('birthplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthplace', to='movie.cauntry', verbose_name='Место рождения')),
                ('genres', models.ManyToManyField(related_name='genre', to='movie.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'актёр',
                'verbose_name_plural': 'актёры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidio_file', models.FileField(upload_to='movi_vidio/', verbose_name='Загрузите видео')),
                ('title', models.CharField(max_length=120, verbose_name='Названея кино')),
                ('desctiption', models.TextField(verbose_name='Описания')),
                ('release_date', models.DateField(verbose_name='Дата выпуска кино')),
                ('premiere_ru', models.DateField(verbose_name='Премьера (РФ)')),
                ('many', models.PositiveBigIntegerField(verbose_name='Сборы по миру $')),
                ('tegline', models.CharField(max_length=25, verbose_name='Слоган фильма')),
                ('reting', models.FloatField(default=0, max_length=5, verbose_name='Рейтинг')),
                ('director', models.CharField(max_length=35, verbose_name='Режиссер')),
                ('writer', models.CharField(max_length=35, verbose_name='Сценарист')),
                ('producer', models.CharField(max_length=35, verbose_name='Продюсер')),
                ('age', models.PositiveBigIntegerField(default=16, verbose_name='Возрастное ограничение')),
                ('actors', models.ManyToManyField(to='movie.actor', verbose_name='Актёры каторые участвовали')),
                ('cauntry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='movie.cauntry', verbose_name='Страна производства')),
                ('genre', models.ManyToManyField(related_name='genres', to='movie.genre', verbose_name='Жанр фильма')),
            ],
            options={
                'verbose_name': 'Кино',
                'verbose_name_plural': 'Кино',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='movie.movie', verbose_name='Кино которых учавствовал'),
        ),
        migrations.CreateModel(
            name='Photos_actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='actor_photo/', verbose_name='Фото')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='movie.actor', verbose_name='Актёр')),
            ],
            options={
                'verbose_name': 'Фтот актёра',
                'verbose_name_plural': 'Фтографии актёрав',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='poster/', verbose_name='Постер филема')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Постер связен')),
            ],
            options={
                'verbose_name': 'Постер',
                'verbose_name_plural': 'Постеры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Имя коментатора')),
                ('like', models.PositiveBigIntegerField(default=0, verbose_name='Лайк')),
                ('dislike', models.PositiveBigIntegerField(default=0, verbose_name='Дислайк')),
                ('catigori_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catigori', to='movie.catigori_review', verbose_name='Отзыв (ха-й,плохой , нетральный)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Кино')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
